'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace MaterialUI2

    Partial Public Class Miembros
        Public Property idMiembro As Integer
        Public Property m_nombre As String
        Public Property m_apellido As String
    
        Public Overridable Property Visitas As ICollection(Of Visitas) = New HashSet(Of Visitas)
    
    End Class

End Namespace
