'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace MaterialUI2

    Partial Public Class ContactosEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=ContactosEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Miembros() As DbSet(Of Miembros)
        Public Overridable Property Visitas() As DbSet(Of Visitas)
    
    End Class

End Namespace
