'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace MaterialUI2

    Partial Public Class Visitas
        Public Property idVisita As Integer
        Public Property motivo_visita As String
        Public Property nombre_completo As String
        Public Property h_entrada As Nullable(Of Date)
        Public Property h_salida As Nullable(Of Date)
        Public Property m_recibio As String
        Public Property idMiembro As Nullable(Of Integer)
    
        Public Overridable Property Miembros As Miembros
    
    End Class

End Namespace
